swagger: "2.0"
info:
  title: "idea_log_api"
  description: "API endpoints for idea_log_api"
  version: "1.0.0"
host: "REGION-PROJECT_ID.cloudfunctions.net"
schemes:
  - "https"
paths:
  /:
    get:
      summary: Get index file
      operationId: getIndexFile
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/get_static_file
      responses:
        '200':
          description: A successful response

  /auth/join:
    get:
      summary: Handle join actions
      operationId: handleJoinAction
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/user_join
      responses:
        '200':
          description: A successful response

  /auth/logout:
    get:
      summary: Handle logout actions
      operationId: logout
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/logout
      responses:
        '200':
          description: A successful response

  /auth/login:
    get:
      summary: Handle login actions
      operationId: login
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/login
      responses:
        '200':
          description: A successful response

  /auth/login/callback:
    get:
      summary: Handle login_callback actions for GET method
      operationId: login_callback_get
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/login_callback
      responses:
        '200':
          description: A successful response
    post:
      summary: Handle login_callback actions for POST method
      operationId: login_callback_post
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/login_callback
      responses:
        '200':
          description: A successful response

  /api/fetch_categories:
    get:
      summary: Handle fetch_categories actions
      operationId: fetch_categories
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/fetch_categories
      responses:
        '200':
          description: A successful response

  /api/fetch_messages:
    get:
      summary: Handle fetch_messages actions
      operationId: fetch_messages
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/fetch_messages
      responses:
        '200':
          description: A successful response

  /api/profile:
    get:
      summary: Fetch profile info
      operationId: profile
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/profile
      responses:
        '200':
          description: A successful response

  /api/update_category:
    get:
      summary: Handle update_category actions
      operationId: update_category
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/update_category
      responses:
        '200':
          description: A successful response

  /api/write_message:
    post:
      summary: Handle write_message actions
      operationId: write_message
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/write_message
      responses:
        '200':
          description: A successful response

  /{dir}/{file}:
    get:
      summary: Get static file
      operationId: getStaticFiles1
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/get_static_file
        path_translation: "APPEND_PATH_TO_ADDRESS"
      parameters:
        - name: dir
          in: path
          required: true
          type: string
        - name: file
          in: path
          required: true
          type: string
      responses:
        '200':
          description: A successful response

  /{dir1}/{dir2}/{file}:
    get:
      summary: Get static file
      operationId: getStaticFiles2
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/get_static_file
        path_translation: "APPEND_PATH_TO_ADDRESS"
      parameters:
        - name: dir1
          in: path
          required: true
          type: string
        - name: dir2
          in: path
          required: true
          type: string
        - name: file
          in: path
          required: true
          type: string
      responses:
        '200':
          description: A successful response

  /{dir1}/{dir2}/{dir3}/{file}:
    get:
      summary: Get static file
      operationId: getStaticFiles3
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/get_static_file
        path_translation: "APPEND_PATH_TO_ADDRESS"
      parameters:
        - name: dir1
          in: path
          required: true
          type: string
        - name: dir2
          in: path
          required: true
          type: string
        - name: dir3
          in: path
          required: true
          type: string
        - name: file
          in: path
          required: true
          type: string
      responses:
        '200':
          description: A successful response
