substitutions:
  _REGION: 'asia-northeast3'
  _PROJECT_ID: 'red-girder-405405'

steps:
  # update project setting and api-config.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud config set project $_PROJECT_ID

  # deploy Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud functions deploy get_static_file --runtime python39 --trigger-http --allow-unauthenticated --entry-point get_static_file --source ./gcp_cloud_functions/get_static_file --region $_REGION

  # create API Gateways and deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        if ! gcloud api-gateway apis describe idea-log-api; then
          gcloud api-gateway apis create idea-log-api --quiet
        fi

        sed -i 's/REGION-PROJECT_ID/${_REGION}-${_PROJECT_ID}/g' api-config.yaml

        if gcloud api-gateway api-configs describe idea-log-api-config --api=idea-log-api; then
          gcloud api-gateway gateways delete idea-log-gateway --location=us-central1 --quiet
          gcloud api-gateway api-configs delete idea-log-api-config --api=idea-log-api --quiet
        fi

        gcloud api-gateway api-configs create idea-log-api-config --api=idea-log-api --openapi-spec=api-config.yaml --backend-auth-service-account=${_PROJECT_ID}@appspot.gserviceaccount.com --quiet

        if ! gcloud api-gateway gateways describe idea-log-gateway --location=us-central1; then
          gcloud api-gateway gateways delete idea-log-gateway --location=us-central1 --quiet
        fi

        gcloud api-gateway gateways create idea-log-gateway --api=idea-log-api --api-config=idea-log-api-config --location=us-central1 --quiet

        gcloud api-gateway gateways describe idea-log-gateway --location=us-central1

timeout: '1600s'
