services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    command: gunicorn flask_server.app:create_app() --bind 0.0.0.0:8000  --access-logfile - --error-logfile - # Launches the 'app' from the flask_server.app module with Gunicorn, accessible on all interfaces at port 8000.
    volumes:
      - ./database:/app/database

  nginx:
    image: nginx:latest
    command: nginx -g "daemon off;" # Ensures NGINX runs in the foreground, keeping the container alive and responsive, by setting global directives.
    depends_on:
      - web
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
