name: Check Formatting & Type Hints on Diff

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint mypy yapf
        pip install --no-cache-dir -r flask_server/requirements-base.txt
        sudo apt-get install -y shfmt

    - name: Check Format on Diff
      run: bin/command/check-diff-format HEAD~1

    - name: Run pytest
      run: |
        FLASK_SECRET_KEY=$(openssl rand -hex 32)
        echo "FLASK_SECRET_KEY=$FLASK_SECRET_KEY" >>flask_server/.env
        echo "SQLALCHEMY_DATABASE_URI=/app/database/db.sqlite" >>flask_server/.env
        sudo mkdir database
        sudo chmod 777 database
        sudo touch database/db.sqlite
        sudo chmod 777 database/db.sqlite
        sudo docker-compose up --build pytest
