name: Python Code Quality

on:
  pull_request:
    paths:
      - '**.py'  # Only run this workflow when a .py file changes in the PR

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Adjust the Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint mypy  # Install pylint and mypy

    - name: Run pylint
      run: pylint **/*.py  # Run pylint on all .py files

    - name: Run mypy
      run: mypy .  # Run mypy on the current directory
